# Generated by Django 5.0.1 on 2024-01-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0003_remove_letter_referred_to_letterdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterdetails',
            name='referred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='letterdetails',
            name='additional_text',
            field=models.TextField(default='readed.'),
        ),
    ]
