# Generated by Django 5.0.1 on 2024-01-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0006_letter_referred_to_group_letter_referred_to_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred', models.BooleanField(default=False)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='erp_app.letter')),
            ],
        ),
    ]
