# Generated by Django 5.0.1 on 2024-01-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0007_letterdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='referred_to_user',
        ),
        migrations.AlterField(
            model_name='letter',
            name='progress',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='letter',
            name='referred_to_group',
            field=models.CharField(blank=True, choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('pm', 'Project Manager')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='LetterDetails',
        ),
    ]
