# Generated by Django 5.0.1 on 2024-01-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0008_remove_letter_referred_to_user_alter_letter_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='recipient',
            field=models.CharField(choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('pm', 'Project Manager'), ('user', 'user')], max_length=50),
        ),
        migrations.AlterField(
            model_name='letter',
            name='referred_to_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
