# Generated by Django 5.0.1 on 2024-01-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0009_alter_letter_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='actions_history',
            field=models.JSONField(default=list),
        ),
    ]
