# Generated by Django 5.0.1 on 2024-01-08 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0010_letter_actions_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_to_group', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_text', models.TextField(blank=True, null=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.letter')),
            ],
        ),
    ]
