# Generated by Django 5.0.1 on 2024-01-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0011_letterdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='recipient',
            field=models.CharField(choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('pm', 'Project Manager'), ('', '')], max_length=50),
        ),
    ]
