# Generated by Django 5.0.1 on 2024-01-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0012_alter_letter_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='reci_get',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
