# Generated by Django 5.0.1 on 2024-01-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0013_letter_reci_get'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='reci_get',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
